version: '3'
services:
  mockapi:
    image: typicode/json-server
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/data/db.json
  
  flutter-app:
    image: tp_flutter-flutter:latest
    ports:
      - "9090:8080" # changé de 8080:8080 à 9090:8080
    volumes:
      - .:/app
    working_dir: /app
    command: flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0